#!/usr/bin/env bash
# Script to configure Nginx with a 301 redirect for /redirect_me

# Exit on error
set -e

apt-get update -y -qq && \
apt-get install nginx -y
apt-get install -y ufw

echo -e "\nSetting up some minor stuff.\n"

# Enable firewall and allow Nginx HTTP
ufw enable
ufw allow 'Nginx HTTP'

# Starting nginx service
service nginx start

# Configure Nginx default site
bash -c 'cat > /etc/nginx/sites-available/default << "EOF"
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    # Redirect /redirect_me to another page
    location /redirect_me {
        return 301 http://rentivunwa250.tech;
    }

    location / {
    	root /var/www/html;
    	index index.html;
        try_files $uri $uri/ =404;
    }

}
EOF'

# Restart Nginx to apply changes
service nginx restart
