#!/usr/bin/env bash
# Script to configure Nginx with a 301 redirect for /redirect_me

# Exit on error
set -e

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Configure Nginx default site
bash -c 'cat > /etc/nginx/sites-available/default << "EOF"
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    # Redirect /redirect_me to another page
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
    	root /var/www/html;
    	index index.html;
        try_files $uri $uri/ =404;
    }

}
EOF'

# Restart Nginx to apply changes
sudo service nginx restart
echo -e "\nRedirection setup completed.\n"
