#!/usr/bin/env bash
# Script to configure Nginx with a 301 redirect for /redirect_me

# Exit on error
set -e

# Update package list and install Nginx
apt-get update -y
apt-get install -y nginx

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

sudo tee /var/www/html/custom_404.html > /dev/null <<'EOF'
Ceci n'est pas une page
EOF


# Configure Nginx default site
bash -c 'cat > /etc/nginx/sites-available/default << "EOF"
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    # Redirect /redirect_me to another page
    location /redirect_me {
        return 301 http://rentivunwa250.tech;
    }

    # Custom error page
    error_page 404 /custom_404.html;
    location = /custom_404.html {
    	root /var/www/html;
	internal;
    }
}
EOF'

# Restart Nginx without using systemctl
service nginx restart

