#!/usr/bin/env bash
# Script to configure Nginx with a 301 redirect for /redirect_me

# Exit on error
set -e

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

sudo tee /var/www/html/custom_404.html > /dev/null <<'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>
EOF


# Configure Nginx default site
bash -c 'cat > /etc/nginx/sites-available/default << "EOF"
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    # Custom error page
    error_page 404 /custome_404.html;
    location = /custome_404.html {
    	internal;
    }
}
EOF'

# Restart Nginx to apply changes
sudo systemctl restart nginx

