#!/usr/bin/env bash
# Script to configure Nginx with a 301 redirect for /redirect_me

# Exit on error
set -e

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

sudo tee /var/www/html/custom_404.html > /dev/null <<'EOF'
<html>
  <body>
    <h1>ici n'est pas ...</h1>
  </body>
</html>
EOF


# Configure Nginx default site
bash -c 'cat > /etc/nginx/sites-available/default << "EOF"
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    # Custom error page
    error_page 404 /custome_404.html;
    location = /custome_404.html {
    	root /var/www/html;
	internal;
    }
}
EOF'

# Restart Nginx without using systemctl
sudo service nginx restart

